### ISSUE TITLE
run.sh fails

### ISSUE THREAD

**Issue by OrfeasLitos** [decrypto-org/TrustIsRisk.js#1]
1) forked repo in OrfeasLitos
2) cloned it locally
3) installed `docker` and `npm` with `pacman`
4) ran `npm install`. The following warnings appeared:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN TrustIsRisk.js@1.0.0 No repository field.
npm WARN The package babel-polyfill is included as both a dev and production dependency.
```
5) ran  `npm run-script typecheck`. Output:
```

> TrustIsRisk.js@1.0.0 typecheck /home/user/Documents/TrustIsRisk.js
> flow check; test $? -eq 0 -o $? -eq 2

Found 0 errors
```
6) Ran `./run.sh`. Output:
`./run.sh: line 3: babel: command not found`

I tried installing it, but Babel is not in `pacman`.
Inside the node_modules there is a ton of babel directories.

**Comment by OrfeasLitos** [comment]
Changed `babel` in line 3 to `node_modules/babel-cli/bin/babel.js` and new errors arise. `./run.sh` Output:
```
src/index.js -> build/index.js
src/service.js -> build/service.js
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
```

**Comment by christosporios** [comment]
Hello Orfeas, thanks for taking the time.

I'll make a PR to fix the first issue.

The second issue is related to your docker installation. Does `docker run hello-world ` work? If not, then the problem is that either:
1. The docker daemon is not running.
2. Your user is not allowed to access the docker daemon, in which case running `usermod -a -G docker <username>` and opening a new terminal session should fix your problem.

**Comment by OrfeasLitos** [comment]
Forgot to refer to the issue in the commit message. Closing manually.
